PAL = "PALETTEFILES"
SF = "SOUNDFILES"
TEXF = "TEXTUREFILES"
MSKF = "MASKFILES"
BCKF = "BACKFILES"
COL = "COLORS"
MAT = "MATERIALS"
SND = "SOUNDS"

SECTIONS = [PAL, SF, TEXF, MSKF, BCKF, COL, MAT, SND]